### ISSUE TITLE
The example code does not work

### ISSUE THREAD

**Issue by saurabhsanthosh** [sparkbyexamples/spark-hbase-connector-examples#2]
Getting the following error while running HBaseSparkInsert :

Exception in thread "main" java.lang.ClassNotFoundException: Failed to find data source: org.apache.spark.sql.execution.datasources.hbase. Please find packages at http://spark.apache.org/third-party-projects.html
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:657)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:244)
	at com.sparkbyexamples.spark.hbase.dataframe.HBaseSparkInsert$.main(HBaseSparkInsert.scala:46)
	at com.sparkbyexamples.spark.hbase.dataframe.HBaseSparkInsert.main(HBaseSparkInsert.scala)

**Comment by SunnyRivers** [comment]
Yes,it does not work
